apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thekjar-com-tls
spec:
  secretName: thekjar-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: thekjar.com
  dnsNames:
    - thekjar.com
    - www.thekjar.com
